travis:
  secure:
    BINSTAR_TOKEN: KwZk0wjXKE26s2Ag18fiiMbG/3MYOP6sfc0BcPfLUAs0XVvKqkq+SdsGAxxpUNUZjqlh3LBPLHu9FCNyH9HkXacV9yXh18BrCa5vKiEGUYmOzh6YDzEHqCDiSvXl7bfXyse3rPrFfkCbrWxoFdzq7ZlM3OcTPGuvI2l4EkyxA53dJPUqlYB4p/+Fkl0UD/s70iArkorEbRVbkzn10M+CRVi1S2r2rGkaviRVdQU9dGvSZNQaYv3znPm5K5wlja24wjFloFlXbpYL0ymjpbBtaa+ebSEJDfrJgyUYZLmWbHiucukaQRzYQ2VPTRXI7r5EqjtGFktf/mUIbRJsS5QL0XVX1v0DzC10hz3/+AvEpV7UDGfaAnMcFLXWB3RGFNJcc9mM8Xl22Dxa7Z0DagZitO6JQRNcdVT9OI6hPGAZsJOJmbKu0xoBQZmuUV1Uv3uUDr2yKpSp9k9A9zMs9zOarsE1DXhKcn8D+EGXHRb2S7sKWffZ3uI/Bl++X5tyeFQAu644OFqQsYyTRyIdeX784879n6+WDlINdzlR8MoNXiBXvVeykJEqyXraO08Eswu2FMz/ldj6DJqLCRDKYSRtYVuOpYszEGfsuXjIeSiHB0bnRLeDQwo7VJTDDEJq9hWS4e23KFdtKWV4eDg2jRL0FAY5NB3SoUHoLFNdzEsk1pI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
